from __future__ import annotations

from collections.abc import Iterable

from .models import Claim, Evidence, Hypothesis, Task, TuningParams


DEMO_EVIDENCE = [
    Evidence(
        source_id="source_001",
        title="U.S. Copyright Office, Copyright Registration Guidance: Works Containing Material Generated by Artificial Intelligence",
        url="https://www.copyright.gov/ai/ai_policy_guidance.pdf",
        source_type="agency_guidance",
        excerpt="The Office requires human authorship and asks applicants to disclaim AI-generated material that is more than de minimis.",
        supports=["h001", "h002", "h003"],
        reliability=0.95,
    ),
    Evidence(
        source_id="source_002",
        title="Thaler v. Perlmutter",
        url="https://www.cadc.uscourts.gov/internet/opinions.nsf/",
        source_type="case_law",
        excerpt="Federal courts have rejected copyright registration where the asserted author was a non-human AI system.",
        supports=["h001"],
        reliability=0.9,
    ),
    Evidence(
        source_id="source_003",
        title="U.S. Copyright Act, 17 U.S.C. Section 102",
        url="https://www.law.cornell.edu/uscode/text/17/102",
        source_type="statute",
        excerpt="Copyright protection subsists in original works of authorship fixed in a tangible medium of expression.",
        supports=["h001", "h002"],
        reliability=0.92,
    ),
    Evidence(
        source_id="source_004",
        title="Open source and AI code provenance diligence pattern",
        url="local://startup-risk-analysis",
        source_type="domain_analysis",
        excerpt="Startups relying on generated code should track prompts, model/provider terms, licenses in retrieved code, and human review history.",
        supports=["h004"],
        reliability=0.72,
    ),
    Evidence(
        source_id="source_005",
        title="Human selection and arrangement counterpoint",
        url="local://human-control-counterpoint",
        source_type="expert_analysis",
        excerpt="Some AI-assisted outputs may include protectable human expression when a person controls selection, arrangement, editing, or code-level changes.",
        supports=["h002", "h003"],
        contradicts=["h001"],
        reliability=0.68,
    ),
]


def collect_evidence(tasks: list[Task], hypotheses: list[Hypothesis], seed_texts: Iterable[str] = ()) -> list[Evidence]:
    task_text = " ".join(task.question.lower() for task in tasks)
    if "ai-generated code" in task_text and "copyright" in task_text:
        evidence = list(DEMO_EVIDENCE)
    else:
        evidence = []

    for index, text in enumerate(seed_texts, start=len(evidence) + 1):
        cleaned = " ".join(text.split())
        if not cleaned:
            continue
        evidence.append(
            Evidence(
                source_id=f"source_{index:03d}",
                title=f"Seed document {index}",
                url=f"local://seed/{index}",
                source_type="seed_text",
                excerpt=cleaned[:500],
                supports=[hypotheses[0].hypothesis_id] if hypotheses else [],
                reliability=0.65,
            )
        )
    return evidence


def claims_from_hypotheses(hypotheses: list[Hypothesis], evidence: list[Evidence], params: TuningParams | None = None) -> list[Claim]:
    params = params or TuningParams()
    claims: list[Claim] = []
    for index, hypothesis in enumerate(hypotheses, start=1):
        supporting = [item.source_id for item in evidence if hypothesis.hypothesis_id in item.supports]
        contradicting = [item.source_id for item in evidence if hypothesis.hypothesis_id in item.contradicts]
        support_score = sum(item.reliability for item in evidence if item.source_id in supporting) / max(1, len(supporting))
        contradiction_penalty = (
            sum(item.reliability for item in evidence if item.source_id in contradicting)
            / max(1, len(contradicting))
            * params.contradiction_penalty_weight
        )
        confidence = max(0.0, min(0.98, support_score - contradiction_penalty))
        status = "supported" if confidence >= params.supported_claim_threshold else "contested" if contradicting else "weak"
        claims.append(
            Claim(
                claim_id=f"c{index:03d}",
                claim=hypothesis.statement,
                supporting_sources=supporting,
                contradicting_sources=contradicting,
                confidence=round(confidence, 2),
                status=status,
            )
        )
    return claims
