from __future__ import annotations

from collections.abc import Iterable

from .models import Claim, Evidence, Hypothesis, Task, TuningParams
from .retrieval import retrieve_live_evidence


DEMO_EVIDENCE = [
    Evidence(
        source_id="source_001",
        title="U.S. Copyright Office, Copyright Registration Guidance: Works Containing Material Generated by Artificial Intelligence",
        url="https://www.copyright.gov/ai/ai_policy_guidance.pdf",
        source_type="agency_guidance",
        excerpt="The Office requires human authorship and asks applicants to disclaim AI-generated material that is more than de minimis.",
        supports=["h001", "h002", "h003"],
        reliability=0.95,
    ),
    Evidence(
        source_id="source_002",
        title="Thaler v. Perlmutter",
        url="https://www.cadc.uscourts.gov/internet/opinions.nsf/",
        source_type="case_law",
        excerpt="Federal courts have rejected copyright registration where the asserted author was a non-human AI system.",
        supports=["h001"],
        reliability=0.9,
    ),
    Evidence(
        source_id="source_003",
        title="U.S. Copyright Act, 17 U.S.C. Section 102",
        url="https://www.law.cornell.edu/uscode/text/17/102",
        source_type="statute",
        excerpt="Copyright protection subsists in original works of authorship fixed in a tangible medium of expression.",
        supports=["h001", "h002"],
        reliability=0.92,
    ),
    Evidence(
        source_id="source_004",
        title="Copyright Office registration consequence for non-human authorship",
        url="https://www.copyright.gov/ai/",
        source_type="agency_guidance",
        excerpt="If material lacks sufficient human authorship, registration may need to exclude that material, creating ownership and diligence risk for software companies.",
        supports=["h004"],
        reliability=0.88,
    ),
    Evidence(
        source_id="source_005",
        title="Open source and AI code provenance diligence pattern",
        url="local://startup-risk-analysis",
        source_type="domain_analysis",
        excerpt="Startups relying on generated code should track prompts, model/provider terms, licenses in retrieved code, and human review history.",
        supports=["h004"],
        reliability=0.72,
    ),
    Evidence(
        source_id="source_006",
        title="Human selection and arrangement counterpoint",
        url="local://human-control-counterpoint",
        source_type="expert_analysis",
        excerpt="Some AI-assisted outputs may include protectable human expression when a person controls selection, arrangement, editing, or code-level changes.",
        supports=["h002", "h003"],
        reliability=0.68,
    ),
]


def collect_evidence(
    tasks: list[Task],
    hypotheses: list[Hypothesis],
    seed_texts: Iterable[str] = (),
    live_retrieval: bool = True,
    source_urls: Iterable[str] = (),
    use_modal: bool = False,
) -> tuple[list[Evidence], dict]:
    task_text = " ".join(task.question.lower() for task in tasks)
    evidence: list[Evidence] = []
    retrieval_stats = {
        "enabled": live_retrieval,
        "attempted_urls": 0,
        "successful_urls": 0,
        "failed_urls": 0,
        "retrieved_urls": [],
        "errors": {},
        "fallback_used": False,
    }

    if live_retrieval:
        live_evidence, stats = retrieve_live_evidence(tasks, hypotheses, source_urls=source_urls, use_modal=use_modal)
        evidence.extend(live_evidence)
        retrieval_stats.update(stats.as_dict())
        retrieval_stats["modal_enabled"] = use_modal
    else:
        retrieval_stats["modal_enabled"] = False

    is_ai_copyright_research = "ai-generated code" in task_text or ("authorship" in task_text and "ai" in task_text)
    if is_ai_copyright_research:
        missing_hypotheses = _missing_supported_hypotheses(evidence, hypotheses)
        source_types = {item.source_type for item in evidence}
        if missing_hypotheses or len(source_types) < 4:
            retrieval_stats["fallback_used"] = True
            evidence.extend(_fallback_evidence_for_missing_hypotheses(evidence, missing_hypotheses, min_source_types=4))

    for index, text in enumerate(seed_texts, start=len(evidence) + 1):
        cleaned = " ".join(text.split())
        if not cleaned:
            continue
        evidence.append(
            Evidence(
                source_id=f"source_{index:03d}",
                title=f"Seed document {index}",
                url=f"local://seed/{index}",
                source_type="seed_text",
                excerpt=cleaned[:500],
                supports=[hypotheses[0].hypothesis_id] if hypotheses else [],
                reliability=0.65,
            )
        )
    return evidence, retrieval_stats


def _missing_supported_hypotheses(evidence: list[Evidence], hypotheses: list[Hypothesis]) -> set[str]:
    supported = {hypothesis_id for item in evidence for hypothesis_id in item.supports}
    return {hypothesis.hypothesis_id for hypothesis in hypotheses} - supported


def _fallback_evidence_for_missing_hypotheses(evidence: list[Evidence], missing_hypotheses: set[str], min_source_types: int = 4) -> list[Evidence]:
    urls = {item.url for item in evidence}
    source_types = {item.source_type for item in evidence}
    fallback: list[Evidence] = []
    next_index = len(evidence) + 1
    for item in DEMO_EVIDENCE:
        if item.url in urls:
            continue
        fills_hypothesis = bool(missing_hypotheses.intersection(item.supports))
        fills_source_type = item.source_type not in source_types and len(source_types) < min_source_types
        if not fills_hypothesis and not fills_source_type:
            continue
        fallback.append(
            Evidence(
                source_id=f"source_{next_index:03d}",
                title=item.title,
                url=item.url,
                source_type=item.source_type,
                excerpt=item.excerpt,
                supports=item.supports,
                contradicts=item.contradicts,
                reliability=item.reliability,
            )
        )
        next_index += 1
        urls.add(item.url)
        source_types.add(item.source_type)
    return fallback


def claims_from_hypotheses(hypotheses: list[Hypothesis], evidence: list[Evidence], params: TuningParams | None = None) -> list[Claim]:
    params = params or TuningParams()
    claims: list[Claim] = []
    for index, hypothesis in enumerate(hypotheses, start=1):
        supporting = [item.source_id for item in evidence if hypothesis.hypothesis_id in item.supports]
        contradicting = [item.source_id for item in evidence if hypothesis.hypothesis_id in item.contradicts]
        support_score = sum(item.reliability for item in evidence if item.source_id in supporting) / max(1, len(supporting))
        contradiction_penalty = (
            sum(item.reliability for item in evidence if item.source_id in contradicting)
            / max(1, len(contradicting))
            * params.contradiction_penalty_weight
        )
        confidence = max(0.0, min(0.98, support_score - contradiction_penalty))
        status = "supported" if confidence >= params.supported_claim_threshold else "contested" if contradicting else "weak"
        claims.append(
            Claim(
                claim_id=f"c{index:03d}",
                claim=hypothesis.statement,
                supporting_sources=supporting,
                contradicting_sources=contradicting,
                confidence=round(confidence, 2),
                status=status,
            )
        )
    return claims
