from __future__ import annotations

from .models import ResearchProgram, StopConditions


def generate_program(goal: str) -> ResearchProgram:
    normalized = goal.lower()
    if "ai-generated code" in normalized and "copyright" in normalized:
        subquestions = [
            "What legal standard controls authorship for AI-generated code?",
            "How do primary authorities treat works generated by AI systems?",
            "When can AI-assisted code still contain protectable human authorship?",
            "What ownership, licensing, and infringement risks would a startup face?",
            "Which contradictions or unsettled questions remain?",
        ]
        evidence_requirements = [
            "Prefer primary legal sources such as statutes, agency guidance, and cases.",
            "Every material claim should cite at least one source.",
            "Separate copyrightability, ownership, and infringement risk.",
            "Flag unresolved or jurisdiction-specific uncertainty.",
        ]
    else:
        subquestions = [
            f"What legal issue is raised by: {goal}?",
            "Which jurisdiction, governing law, and authority hierarchy control the analysis?",
            "Which primary legal authorities support or contradict the likely answer?",
            "What practical legal risks, compliance duties, or liability exposure follow?",
            "Which unsettled legal questions or factual assumptions could change the answer?",
        ]
        evidence_requirements = [
            "Prefer statutes, binding cases, regulations, agency guidance, and official materials.",
            "Every material legal claim should cite an authority or be marked as unsupported.",
            "Distinguish binding authority from persuasive or secondary sources.",
            "Track jurisdiction, procedural posture, and temporal validity.",
            "Do not present the output as legal advice.",
        ]

    return ResearchProgram(
        objective=goal.strip(),
        subquestions=subquestions,
        evidence_requirements=evidence_requirements,
        success_metrics=[
            "Coverage of all subquestions",
            "Citation grounding",
            "Source diversity",
            "Contradiction resolution",
            "Low unresolved critical questions",
        ],
        stop_conditions=StopConditions(),
    )


def program_to_markdown(program: ResearchProgram) -> str:
    stops = program.stop_conditions
    lines = [
        "# Research Program",
        "",
        "## Legal Metadata",
        f"- Domain: {program.legal_metadata.domain}",
        f"- Jurisdiction: {program.legal_metadata.jurisdiction}",
        f"- Practice area: {program.legal_metadata.practice_area}",
        f"- Citation style: {program.legal_metadata.citation_style}",
        f"- Risk posture: {program.legal_metadata.risk_posture}",
        f"- Temporal sensitivity: {program.legal_metadata.temporal_sensitivity}",
        f"- Uncertainty policy: {program.legal_metadata.uncertainty_policy}",
        "",
        "## Legal Authority Hierarchy",
        *[f"- {item}" for item in program.legal_metadata.authority_hierarchy],
        "",
        "## Required Legal Source Types",
        *[f"- {item}" for item in program.legal_metadata.required_source_types],
        "",
        "## Objective",
        program.objective,
        "",
        "## Subquestions",
        *[f"- {item}" for item in program.subquestions],
        "",
        "## Evidence Requirements",
        *[f"- {item}" for item in program.evidence_requirements],
        "",
        "## Success Metrics",
        *[f"- {item}" for item in program.success_metrics],
        "",
        "## Stop Conditions",
        f"- Confidence >= {stops.confidence:.0%}",
        f"- Citation grounding >= {stops.citation_grounding:.0%}",
        f"- Open questions <= {stops.open_questions}",
        f"- Objective completion >= {stops.objective_completion:.0%}",
        "",
    ]
    return "\n".join(lines)
