from __future__ import annotations

from .models import ResearchProgram, StopConditions


LEGAL_KEYWORDS = {"copyright", "authorship", "legal", "law", "startup", "liability", "infringement"}


def generate_program(goal: str) -> ResearchProgram:
    normalized = goal.lower()
    is_legal = any(keyword in normalized for keyword in LEGAL_KEYWORDS)

    if is_legal:
        subquestions = [
            "What legal standard controls authorship for AI-generated code?",
            "How do primary authorities treat works generated by AI systems?",
            "When can AI-assisted code still contain protectable human authorship?",
            "What ownership, licensing, and infringement risks would a startup face?",
            "Which contradictions or unsettled questions remain?",
        ]
        evidence_requirements = [
            "Prefer primary legal sources such as statutes, agency guidance, and cases.",
            "Every material claim should cite at least one source.",
            "Separate copyrightability, ownership, and infringement risk.",
            "Flag unresolved or jurisdiction-specific uncertainty.",
        ]
    else:
        subquestions = [
            f"What is the current state of evidence for: {goal}?",
            "Which explanations or hypotheses best account for the evidence?",
            "Which sources support or contradict each candidate answer?",
            "What gaps would materially change the conclusion?",
        ]
        evidence_requirements = [
            "Prefer primary and authoritative sources.",
            "Every material claim should cite evidence.",
            "Track contradictory evidence explicitly.",
        ]

    return ResearchProgram(
        objective=goal.strip(),
        subquestions=subquestions,
        evidence_requirements=evidence_requirements,
        success_metrics=[
            "Coverage of all subquestions",
            "Citation grounding",
            "Source diversity",
            "Contradiction resolution",
            "Low unresolved critical questions",
        ],
        stop_conditions=StopConditions(),
    )


def program_to_markdown(program: ResearchProgram) -> str:
    stops = program.stop_conditions
    lines = [
        "# Research Program",
        "",
        "## Objective",
        program.objective,
        "",
        "## Subquestions",
        *[f"- {item}" for item in program.subquestions],
        "",
        "## Evidence Requirements",
        *[f"- {item}" for item in program.evidence_requirements],
        "",
        "## Success Metrics",
        *[f"- {item}" for item in program.success_metrics],
        "",
        "## Stop Conditions",
        f"- Confidence >= {stops.confidence:.0%}",
        f"- Citation grounding >= {stops.citation_grounding:.0%}",
        f"- Open questions <= {stops.open_questions}",
        f"- Objective completion >= {stops.objective_completion:.0%}",
        "",
    ]
    return "\n".join(lines)
